
platform :ios, “10.2”

xcodeproj 'vitagou.xcodeproj'  
 target “vitagou” do
 pod 'Masonry', '~> 0.6.4'
 pod 'AFNetworking', '~> 2.6.3'
 pod 'TouchJSON', '~> 1.1'
 pod 'SDWebImage', '~> 3.7.1'
 pod 'FMDB', '~> 2.5'
 pod 'jastor', '~> 0.2.1'
 pod 'MJExtension', '~> 3.0.13'
 pod 'MBProgressHUD', '~> 0.9.2'
 pod 'ActionSheetPicker-3.0', '~> 2.0.3'
 pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
 pod 'MJRefresh'
 pod 'SDCycleScrollView'
 end
