# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'lvdouyi' do

  # pod 'AFNetworking', '~> 3.0'
  # pod 'Masonry','~>1.1.0'
  # pod 'MJExtension'
  # pod 'SDWebImage', '~> 4.0'
  # pod 'FMDB'
  #pod 'MJRefresh'
  # pod 'SVProgressHUD'#
   pod 'YYKit'#富文本等
   
   pod 'WebViewJavascriptBridge', '~> 6.0'
  # pod 'M13ProgressSuite'#进度条
   #pod 'SDCycleScrollView','~> 1.75'#轮播图
  # pod 'MOFSPickerManager'#三级联动
  # pod 'Toast', '~> 4.0.0'
  # pod 'FDFullscreenPopGesture', '1.1'
  # pod 'HMQRCodeScanner'#二维码
  # pod 'TZImagePickerController'#图片选择器
  # pod 'ZJScrollPageView'#仿网易滑动tab
  # pod 'IQKeyboardManager'#键盘管理
  # pod 'Reachability'#网络监控
  # pod 'MBProgressHUD'#蒙版
   #pod 'Colours'#色值

   
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

end
