# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'AcculifeCommunication' do

   pod 'WKWebViewJavascriptBridge', '~> 1.1.0'
   use_frameworks!

  

end
